; NightMare Network DS18B20 example. Build against this checkout.
[env]
framework = arduino
monitor_speed = 115200
monitor_filters = send_on_enter, esp32_exception_decoder
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.39/platform-espressif32.zip
board_build.partitions = min_spiffs.csv
lib_deps =
    symlink://../..
    bblanchon/ArduinoJson@^6.21.3
    paulstoffregen/OneWire@^2.3.8
    milesburton/DallasTemperature@^3.11.0

[env:esp32c3-supermini]
board = nologo_esp32c3_super_mini
build_flags = -D BOARD_C3_V1

[env:esp32doit-devkit-v1]
board = esp32doit-devkit-v1
build_flags = -D BOARD_ESP32_V1
monitor_rts = 0
monitor_dtr = 0
