#pragma once

#define NM_ENABLE_SETTINGS 0
#define NM_ENABLE_RESOURCES 0
#define NM_ENABLE_NETWORK 0
#define NM_ENABLE_CONSOLE 0
#define NM_ENABLE_WIFI 0
#define NM_ENABLE_MQTT 0
#define NM_ENABLE_TELEMETRY 0
#define NM_ENABLE_SCHEDULER 0
#define NM_ENABLE_JOBS 0
#define NM_ENABLE_TIME_SYNC 0
